galaxy_info:
  author: Annet Vargas Dueñas
  description: >
    Role to configure a production server baseline for personal projects.
    Configures security services, log rotation for system and application logs,
    and basic hardening of SSH, AppArmor, UFW, Fail2ban, Aduditd, Apache, PHP-FPM, MySQL, Node.js API, Caddy, and Cloudflare Tunnel.
    Intended for personal use; while functional, it is in testing and not guaranteed to be production-ready.
  license: MIT
  min_ansible_version: 0.1.0
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  categories:
    - security
    - baseline
  collections:
    - community.mysql
    - community.hashi_vault

dependencies:
  - robertdebock.bootstrap