---
- name: Configure production server baseline
  hosts: all
  become: true

  pre_tasks:
    - name: Detect if running inside GitHub Codespaces
      set_fact:
        is_codespace: "{{ ansible_env.CODESPACES is defined }}"
      tags:
        - always
        - env_detect

  roles:
    - role: security
      vars:
        merge_vars: true
        # merge_vars_verified: true
        system_user_ssh_public_key: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/ssh key=system_user_public_key')['system_user_public_key'] }}"
        email_app_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/exim4 key=email_app_password')['email_app_password'] }}"
        cloudflare_tunnel_token: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/cloudflare key=tunnel_token')['tunnel_token'] }}"