---
- name: Configure and Install Caddy
  block:
    - name: Download and convert Caddy GPG key
      ansible.builtin.shell: |
        curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/gpg.key | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      tags:
        - dependencies
        - install

    - name: Add Caddy's official apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
        state: present
        filename: caddy-stable
        update_cache: yes
      tags:
        - dependencies
        - install

    - name: Install Caddy
      ansible.builtin.apt:
        name: caddy
        state: present
        update_cache: yes
      tags:
        - install

    - name: Create directory for Caddy access logs and set permissions
      ansible.builtin.file:
        path: "{{ caddy_proxy.log_path }}"
        state: directory
        owner: caddy
        group: caddy
        mode: '0750'
      tags:
        - logrotate
        - caddy_logs

    - name: SUCCESS -> Caddy installed and service configured successfully
      ansible.builtin.debug:
        msg: "Caddy installed and service configured successfully."
      tags:
        - logrotate
        - caddy_logs
        - success
        - success:stage
  
  rescue:
    - name: ERROR -> Caddy installation or service configuration failed
      ansible.builtin.fail:
        msg: "Caddy installation or service configuration failed. Check the logs for details."
      tags:
        - logrotate
        - caddy_logs

  tags:
    - caddy