---
# ====================================================
# Cloudflare Tunnel
# ====================================================
cloudflared_path: /etc/cloudflared
cloudflared_binary_path: /usr/local/bin/cloudflared
cloudflared_log_path: /var/log/cloudflared

# ====================================================
# Fail2ban
# ====================================================
fail2ban_filters_path: /etc/fail2ban/filter.d
fail2ban_filters:
  - name: mysqld-auth
    dest_file: mysqld-auth.conf
    content: |
      [Definition]
      failregex = Access denied for user .* from <HOST>
      ignoreregex =
  - name: apache-badbots
    dest_file: apache-badbots.conf
    content: |
      [Definition]
      failregex = ^<HOST> -.*"(GET|POST|HEAD).+" 200 .*"(?:acunetix|sqlmap|nikto|libwww-perl|curl|python-requests|nmap|masscan|fuzzer|badbot|wget|HTTrack|httpclient|harvest|scrapy|python|scan|bot|crawler).*"$
      ignoreregex =
  - name: php-login
    dest_file: php-login.conf
    content: |
      [Definition]
      failregex = <HOST> -.*"(POST|GET) /.*(login|signin|auth)\.php.* HTTP/.*" (401|403|404)
      ignoreregex =
  - name: portfolio_api
    dest_file: portfolio_api.conf
    content: |
      [Definition]
      failregex = ^.*\[(?:ProbingSuspiciousRoute|DisallowedMethod|AuthFailed401|AuthFailed403|SQLInjectionAttempt|XSSAttempt|TokenTampering)\].*from <HOST>.*$
      ignoreregex =
  - name: caddy-badbots
    dest_file: caddy-badbots.conf
    content: |
      [Definition]
      failregex = ^<HOST> -.*"(GET|POST|HEAD).+" 200 .*"(?:acunetix|sqlmap|nikto|libwww-perl|curl|python-requests|nmap|masscan|fuzzer|badbot|wget|HTTrack|httpclient|harvest|scrapy|python|scan|bot|crawler).*"$
      ignoreregex =

fail2ban_jails_count: 6
fail2ban_jails:
  - name: sshd
    jail_name: sshd
    enabled: true
    port: ssh
    maxretry: 4
    filter: sshd
  - name: mysql
    jail_name: mysqld-auth
    enabled: true
    port: 3306
    maxretry: 3
    filter: mysqld-auth
  - name: apache2
    jail_name: apache-badbots
    enabled: true
    maxretry: 1
    findtime: 3600
    bantime: 43200
    filter: apache-badbots
  - name: php-fpm
    jail_name: php-login
    enabled: true
    port: http,https
    maxretry: 5
    findtime: 600
    filter: php-login
  - name: portfolio_api
    jail_name: portfolio_api
    enabled: true
    maxretry: 1
    bandtime: 86400
    filter: portfolio_api
  - name: caddy
    jail_name: caddy-badbots
    enabled: true
    port: http,https
    maxretry: 2
    findtime: 3600
    bantime: 86400
    filter: caddy-badbots

# ====================================================
# Logrotate
# ====================================================

# Note: The tags within the 'all_logrotate_service_tags' variable are centralized here to clearly
# show its relationship with 'log_files_services'. While it could be placed in
# tasks/logrotate.yml, this approach simplifies the management of logrotate tags.

all_logrotate_service_tags:
  - ssh
  - ufw
  - fail2ban
  - mysql
  - apache
  - php
  - php-fpm
  - portfolio_api
  - node_api
  - caddy_reports
  - caddy
  - unattended-upgrades
  - cloudflare_tunnel

# AppArmor does not generate a dedicated log for logrotate.
# Adjust php_fpm_logrotate.conf if using specific PHP-FPM pool logs.
log_files_services:
  - name: sshd
    log_path: /var/log/auth.log
    log_check_type: directory # Directory check for Codespace (no syslog). Change to file check on VM.
    src_file: sshd_logrotate.conf
    is_template: false
  - name: ufw
    log_path: /var/log/ufw.log
    log_check_type: directory
    src_file: ufw_logrotate.conf
    is_template: false
  - name: fail2ban
    log_path: /var/log/fail2ban.log
    log_check_type: file
    src_file: fail2ban_logrotate.conf
    is_template: false
  - name: mysql
    log_path: /var/log/mysql/error.log
    log_check_type: file
    src_file: mysql_logrotate.conf.j2
    is_template: true
  - name: apache2
    log_path: /var/log/apache2/*-access.log
    log_check_type: directory
    src_file: apache_logrotate.conf
    is_template: false
  - name: php-fpm
    log_path: "/var/log/php*-fpm.log"
    log_check_type: directory
    src_file: php_fpm_logrotate.conf
    is_template: false
  - name: portfolio_api
    log_path: /var/log/portfolio_api/combined.log
    log_check_type: file
    src_file: node_api_logrotate.conf.j2
    is_template: true
  - name: node_manager
    log_path: /var/log/node
    log_check_type: directory
    src_file: node_manager_logrotate.conf.j2
    is_template: true
  - name: caddy
    log_path: "/var/log/caddy/*-access.log"
    log_check_type: directory
    src_file: caddy_logrotate.conf
    is_template: false
  - name: unattended-upgrades
    log_path: /var/log/unattended-upgrades
    log_check_type: directory
    src_file: unattended-upgrades_logrotate.conf
    is_template: false
  - name: cloudflare_tunnel
    log_path: /var/log/cloudflared/portfolio-tunnel/cloudflared.log
    log_check_type: file
    src_file: cloudflare_tunnel_logrotate.conf.j2
    is_template: true