---
- name: restart_postfix_vm
  ansible.builtin.systemd:
    name: postfix
    state: restarted
  when: not is_codespace

- name: restart_postfix_codespace
  ansible.builtin.command: "service postfix restart"
  changed_when: false
  when: is_codespace

- name: restart_ssh_vm
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  when: not is_codespace

- name: restart_ssh_codespace
  ansible.builtin.command: "service ssh restart"
  changed_when: false
  when: is_codespace

- name: restart_apache_vm
  ansible.builtin.systemd:
    name: apache2
    state: restarted
  when: not is_codespace

- name: restart_apache_codespace
  ansible.builtin.command: "service apache2 restart"
  changed_when: false
  when: is_codespace

- name: reload_mysql_privileges
  ansible.builtin.command: >
                    mysqladmin --user=root --password={{ mysql_root_password }} reload
  no_log: true

- name: restart_mysql_vm
  ansible.builtin.systemd:
    name: mysql
    state: restarted
  when: not is_codespace

- name: restart_mysql_codespace
  ansible.builtin.command: "service mysql restart"
  changed_when: false
  when: is_codespace

- name: restart_auditd_vm
  ansible.builtin.systemd:
    name: auditd
    state: restarted
  when: not is_codespace

- name: restart_auditd_codespace
  ansible.builtin.command: "service auditd restart"
  changed_when: false
  when: is_codespace

- name: restart_unattended-upgrades_vm
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted
  when: not is_codespace

- name: restart_unattended-upgrades_codespace
  ansible.builtin.command: "service unattended-upgrades restart"
  changed_when: false
  when: is_codespace