# ====================================================
# Auditd
# ====================================================
auditd_manage_rules: true
auditd_rules:
  # Execve auditd rule
  - syscall: execve
    action: always
    filter: exit
    arch: b64
    filters:
      - auid>=1000
      - auid!=4294967295
    keyname: exec-watches
  # Critical system files
  - file: /etc/passwd
    permissions: [write, attribute_change, read]
    keyname: passwd-watch
  - file: /etc/shadow
    permissions: [read, write]
    keyname: shadow-watch
  - file: /etc/group
    permissions: [write, attribute_change, read]
    keyname: group-watch
  - file: /etc/gshadow
    permissions: [write, attribute_change, read]
    keyname: gshadow-watch
  - file: /etc/sudoers
    permissions: [write]
    keyname: sudoers-watch
  # SSH
  - file: /etc/ssh/sshd_config
    permissions: [write, attribute_change, read]
    keyname: sshd-config-watch
  # UFW
  - file: /var/log/ufw.log
    permissions: [write]
    keyname: ufw-log
  # Fail2ban
  - file: /var/log/fail2ban.log
    permissions: [write]
    keyname: fail2ban-log
  # Auditd
  - file: /var/log/audit/audit.log
    permissions: [write]
    keyname: auditd-log
  # MySQL
  - file: /usr/bin/mysql
    permissions: [execute]
    keyname: mysql-access
  - file: /var/run/mysqld/mysqld.sock
    permissions: [read, write]
    keyname: mysql-socket
  - file: /etc/mysql/my.cnf
    permissions: [write, attribute_change, read]
    keyname: mysql-cnf-watch
  # Apache
  - file: /etc/apache2/
    permissions: [write, attribute_change]
    keyname: apache-conf
  - file: /usr/sbin/apache2
    permissions: [execute]
    keyname: apache-binary
  # PHP-FPM
  - file: /etc/php/*/fpm/php.ini
    permissions: [write, attribute_change, read]
    keyname: php-fpm-ini
  - file: /etc/php/*/cli/php.ini
    permissions: [write, attribute_change, read]
    keyname: php-cli-ini
  - file: /etc/php/*/fpm/pool.d/www.conf
    permissions: [write, attribute_change, read]
    keyname: php-fpm-pool
  # PHP-FPM logs
  - file: /var/log/php*-fpm.log
    permissions: [write]
    keyname: php-fpm-log
  # Caddy
  - file: /etc/caddy/
    permissions: [write, attribute_change, read]
    keyname: caddy-conf
  - file: /usr/bin/caddy
    permissions: [execute]
    keyname: caddy-binary
  # Caddy logs
  - file: /var/log/caddy/*-access.log
    permissions: [write, attribute_change]
    keyname: caddy-access
  # Cloudflared
  - file: /usr/local/bin/cloudflared
    permissions: [execute]
    keyname: cloudflared-exec
  - file: /etc/cloudflared/config.yml
    permissions: [write, attribute_change, read]
    keyname: cloudflared-config
  # Cloudflared logs
  - file: /var/log/cloudflared.log
    permissions: [read, write, attribute_change]
    keyname: cloudflared-logs